name: portfolio
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  dotted_line: ^3.2.2
  firebase_core: ^3.3.0
  firebase_storage: ^12.1.3
  cloud_firestore: ^5.6.8
  flutter:
    sdk: flutter
  seo_renderer: ^0.6.0
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_svg: ^2.1.0
  gap: ^3.0.1
  riverpod_annotation: ^2.6.1
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  shared_preferences: ^2.1.0
  google_fonts: ^6.2.1
  flutter_staggered_grid_view: ^0.7.0
  go_router: ^14.2.3
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  url_launcher: ^6.3.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.5
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5
  riverpod: ^2.0.0
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  flutter_gen_runner: ^5.10.0

flutter:
  generate: true
  uses-material-design: true
  
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/me.jpeg

dependency_overrides:
  _fe_analyzer_shared: ^82.0.0
  analyzer: ^7.4.5
  vector_math: ^2.2.0